services:
  backend:
    image: pm-report-backend:2025-11-04
    container_name: pm-report-backend
    ports: ["17500:17500"]
    networks:
      pm_net:
        aliases:
          - pm-report-backend

  frontend:
    image: pm-report-frontend:2025-11-04
    container_name: pm-report-frontend
    environment:
      - BACKEND_URL=http://pm-report-backend:17500
    ports: ["17501:17501"]
    networks:
      pm_net:
        aliases:
          - pm-report-frontend

networks:
  pm_net:
    driver: bridge
